<?php
/**
 * Copyright © element119. All rights reserved.
 * See LICENCE.txt for licence details.
 */
declare(strict_types=1);

use Element119\AdminRedisReport\Model\RedisInfo;
use Magento\Backend\Block\Template;
use Magento\Framework\Escaper;

/** @var Escaper $escaper */
/** @var Template $block */
/** @var array $redisInfo */
/** @see RedisInfo::get() */
$redisInfo = $block->getData('redis_info');
$historicData = $block->getData('historic_redis_data');
$connectionsHistory = array_column($historicData, 'connections');
?>
<section id="connections">
    <h2><?= $escaper->escapeHtml(__('Connections')); ?></h2>

    <div class="connections-wrapper">
        <div class="connections-data">
            <h3><?= $escaper->escapeHtml(__('Live Data Snapshot')); ?></h3>
            <ul class="data-list">
                <?php foreach ($redisInfo['connections'] as $key => $value): ?>
                    <li>
                        <b><?= $escaper->escapeHtml(__($key)); ?>:</b>
                        <?= $escaper->escapeHtml($value); ?>
                    </li>
                <?php endforeach; ?>
            </ul>
        </div>

        <?php if ($connectionsHistory): ?>
            <div class="connections-charts">
                <h3><?= $escaper->escapeHtml(__('History')); ?></h3>
                <div class="connections-chart">
                    <canvas id="connections-chart"
                            width="1250"
                            height="500"/>
                    <script type="text/x-magento-init">
                        {
                            "#connections-chart": {
                                "Element119_AdminRedisReport/js/chart": {
                                    "type": "line",
                                    "data": {
                                        "labels": <?= /** @noEscape */ json_encode(array_keys($historicData)); ?>,
                                        "datasets": [
                                            {
                                                "label": "<?= $escaper->escapeJs(__('Max. Clients')); ?>",
                                                "data": <?= /** @noEscape */ json_encode(
                                                    array_column($connectionsHistory, 'Max. Clients')
                                                ); ?>
                                            },
                                            {
                                                "label": "<?= $escaper->escapeJs(__('Connected Clients')); ?>",
                                                "data": <?= /** @noEscape */ json_encode(
                                                    array_column($connectionsHistory, 'Connected Clients')
                                                ); ?>
                                            },
                                            {
                                                "label": "<?= $escaper->escapeJs(__('Cluster Connections')); ?>",
                                                "data": <?= /** @noEscape */ json_encode(
                                                    array_column($connectionsHistory, 'Cluster Connections')
                                                ); ?>
                                            },
                                            {
                                                "label": "<?= $escaper->escapeJs(__('Rejected Connections')); ?>",
                                                "data": <?= /** @noEscape */ json_encode(
                                                    array_column($connectionsHistory, 'Rejected Connections')
                                                ); ?>
                                            }
                                        ]
                                    },
                                    "options": {
                                        "responsive": true,
                                        "interaction": {
                                            "mode": "index",
                                            "intersect": false
                                        },
                                        "stacked": false,
                                        "plugins": {
                                            "legend": {
                                                "position": "top"
                                            }
                                        },
                                        "scales": {
                                            "y": {
                                                "beginAtZero": true
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    </script>
                </div>
            </div>
        <?php endif; ?>
    </div>
</section>
